# Generated by Django 5.2.4 on 2025-08-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('licence_number', models.CharField(max_length=15, unique=True)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'truck'), ('van', 'van')], max_length=5)),
                ('max_capacity', models.PositiveIntegerField(help_text='Max capacity of the vehicle in kg')),
                ('cost_per_km', models.FloatField(help_text='Cost of transport in €/km')),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management_core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15, unique=True)),
                ('customer_name', models.CharField(max_length=15)),
                ('pickup_address', models.CharField(max_length=15)),
                ('delivery_address', models.CharField(max_length=15)),
                ('weight', models.FloatField(help_text='Total weight of the load in kg')),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('in transit', 'in transit'), ('delivered', 'delivered'), ('closed', 'closed')], default='new')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_management_core.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_management_core.vehicle')),
            ],
        ),
    ]
