# Generated by Django 5.2.4 on 2025-08-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport_management_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(default="", max_length=100)),
                ("x_coordinate", models.FloatField()),
                ("y_coordinate", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_delivery",
                to="transport_management_core.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_pick_up",
                to="transport_management_core.address",
            ),
        ),
    ]
