# Generated by Django 5.2.4 on 2025-08-10 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "transport_management_core",
            "0002_address_alter_order_delivery_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("x_coordinate", "y_coordinate")},
        ),
    ]
